nyan:sys-apps/nvrm: RDEPEND on libXext
libnvidia-glsi.so depends on libXext.
Enforce this dependency explicitly to avoid linker failure when linking
an executable with libEGL if libXext is not present:

warning: libXext.so.6, needed by /build/nyan/usr/lib/libnvidia-glsi.so.19.014, not found (try using -rpath or -rpath-link)
/build/nyan/usr/lib/libnvidia-glsi.so.19.014: undefined reference to `XextCreateExtension'
/build/nyan/usr/lib/libnvidia-glsi.so.19.014: undefined reference to `XMissingExtension'
/build/nyan/usr/lib/libnvidia-glsi.so.19.014: undefined reference to `XextAddDisplay'
/build/nyan/usr/lib/libnvidia-glsi.so.19.014: undefined reference to `XextRemoveDisplay'
/build/nyan/usr/lib/libnvidia-glsi.so.19.014: undefined reference to `XextFindDisplay'

Signed-off-by: Daniel Kurtz <djkurtz@chromium.org>

BUG=chrome-os-partner:28905
TEST=emerge-nyan --unmerge nvrm glmark2 libXext
     emerge-nyan nvrm
   => Should build libXext and nvrm
     emerge-nyan glmark2
   => Should build successfully

Change-Id: I286bb660da806d2fbbb94d79b56cc20cc17e517d
Reviewed-on: https://chromium-review.googlesource.com/200543
Reviewed-by: Katie Roberts-Hoffman <katierh@chromium.org>
Reviewed-by: Dylan Reid <dgreid@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Andrew Chew <achew@nvidia.com>
Commit-Queue: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>